"""LLM evidence-reasoning service (Phase 5).

Runs exactly ONE structured LLM call per analysis. The LLM is an *interpreter*
of the engine JSON, never the risk calculator and never a fraud detector:

* It receives the actual structured engine outputs (built by
  :func:`app.intelligence.explanation.build_llm_context`) — no raw images.
* It is instructed to stay grounded, invent nothing, flag missing information,
  and never convert anomaly scores into probabilities.
* Its output is parsed into the structured :class:`LLMEvaluation` schema.
* Anti-hallucination guards drop any key finding whose source is not one of the
  real engines.
* On ANY failure (disabled, not installed, no key, network, bad JSON) it returns
  an explicit ``UNAVAILABLE`` result — the deterministic assessment stands.

The LLM can never override deterministic facts: its output lives in a separate
``llm`` field and only ``agreement_with_risk`` compares the two.
"""
from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from app.api.schemas.document import ScreeningResponse
from app.intelligence.explanation import build_llm_context
from app.intelligence.llm.base import LLMProvider, LLMProviderError
from app.intelligence.llm.providers import NullLLMProvider
from app.intelligence.schemas import (
    FusedEvidence,
    LLMEvaluation,
    LLMKeyFinding,
    LLMStatus,
    RiskAssessment,
    RiskLevel,
)

_VALID_SOURCES = {"rules", "forensics", "biometrics", "ocr"}
_VALID_IMPORTANCE = {"HIGH", "MEDIUM", "LOW"}

SYSTEM_PROMPT = (
    "You are evaluating structured evidence generated by independent, "
    "automated document-analysis engines (a deterministic rules engine, an "
    "image-forensics engine, and a biometric face-verification engine).\n\n"
    "Treat the supplied JSON as the ONLY authoritative evidence for this "
    "analysis. Your job is to interpret and explain it for a human officer, "
    "not to decide whether the document is genuine or fake.\n\n"
    "Strict rules:\n"
    "- Do NOT invent findings, document fields, forensic anomalies, biometric "
    "scores, database/government checks, or identity records. If information is "
    "missing, say it is missing.\n"
    "- Do NOT convert anomaly scores or similarities into probabilities unless "
    "they are explicitly provided as calibrated probabilities (they are not).\n"
    "- Do NOT claim an anomaly proves fraud, and do NOT contradict the engine "
    "JSON (e.g. if rules report a date-of-birth mismatch, never say it matches).\n"
    "- Do NOT override the deterministic risk level; you may note agreement or "
    "disagreement with it.\n"
    "- Identify corroboration (independent engines agreeing) and contradictions "
    "(mixed evidence, e.g. a forensic photo anomaly alongside a biometric "
    "match). A biometric match does not eliminate a document anomaly.\n\n"
    "Respond with ONLY a single JSON object (no prose, no code fences) with "
    "these keys:\n"
    "{\n"
    '  "summary": str,\n'
    '  "key_findings": [{"source": "rules|forensics|biometrics|ocr", '
    '"finding": str, "importance": "HIGH|MEDIUM|LOW"}],\n'
    '  "corroboration": [str],\n'
    '  "contradictions": [str],\n'
    '  "uncertainties": [str],\n'
    '  "suggested_action": "NO_ADDITIONAL_ACTION|MANUAL_REVIEW|'
    'ENHANCED_VERIFICATION|ESCALATE",\n'
    '  "agreement_with_risk": "AGREE|PARTIAL|DISAGREE"\n'
    "}"
)


class LLMEvaluator:
    """Builds the grounded prompt, calls the provider, validates the output."""

    def __init__(self, provider: Optional[LLMProvider] = None):
        self._provider = provider or NullLLMProvider()

    @property
    def provider(self) -> LLMProvider:
        return self._provider

    def evaluate(
        self,
        response: ScreeningResponse,
        fused: FusedEvidence,
        risk: RiskAssessment,
    ) -> LLMEvaluation:
        model = getattr(self._provider, "model", None)
        if not self._provider.is_available():
            return LLMEvaluation.unavailable(
                "LLM provider is not available/configured.", model=model
            )

        context = build_llm_context(response, fused, risk)
        user = (
            "Structured evidence (authoritative JSON):\n"
            + json.dumps(context, ensure_ascii=False, indent=2)
            + "\n\nProduce the JSON object described in the instructions."
        )

        try:
            raw = self._provider.complete(SYSTEM_PROMPT, user)
        except LLMProviderError as exc:
            return LLMEvaluation.unavailable(str(exc), model=model)
        except Exception as exc:  # last-resort guard — never break the analysis
            return LLMEvaluation.unavailable(f"Unexpected LLM error: {exc!r}", model=model)

        parsed = _extract_json(raw)
        if parsed is None:
            return LLMEvaluation.unavailable(
                "LLM response was not valid JSON.", model=model
            )
        return _to_evaluation(parsed, risk, model)


# ---------------------------------------------------------------------------
# Parsing / validation
# ---------------------------------------------------------------------------
def _extract_json(text: str) -> Optional[Dict[str, Any]]:
    """Best-effort extraction of the first JSON object from the model text."""
    text = text.strip()
    if text.startswith("```"):
        # Strip a ```json ... ``` fence if the model added one.
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:]
    try:
        return json.loads(text)
    except Exception:
        pass
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except Exception:
            return None
    return None


def _to_evaluation(
    data: Dict[str, Any], risk: RiskAssessment, model: Optional[str]
) -> LLMEvaluation:
    key_findings: List[LLMKeyFinding] = []
    for kf in data.get("key_findings", []) or []:
        if not isinstance(kf, dict):
            continue
        source = str(kf.get("source", "")).lower().strip()
        # Anti-hallucination guard: drop findings not attributed to a real engine.
        if source not in _VALID_SOURCES:
            continue
        importance = str(kf.get("importance", "MEDIUM")).upper().strip()
        if importance not in _VALID_IMPORTANCE:
            importance = "MEDIUM"
        finding = str(kf.get("finding", "")).strip()
        if not finding:
            continue
        key_findings.append(
            LLMKeyFinding(source=source, finding=finding, importance=importance)
        )

    suggested = data.get("suggested_action")
    suggested = str(suggested).upper().strip() if suggested else None

    agreement = data.get("agreement_with_risk")
    agreement = str(agreement).upper().strip() if agreement else None
    agreement = _reconcile_agreement(agreement, suggested, risk)

    return LLMEvaluation(
        status=LLMStatus.COMPLETED,
        model=model,
        summary=str(data.get("summary", "")).strip(),
        key_findings=key_findings,
        corroboration=[str(x) for x in (data.get("corroboration") or []) if x],
        contradictions=[str(x) for x in (data.get("contradictions") or []) if x],
        uncertainties=[str(x) for x in (data.get("uncertainties") or []) if x],
        suggested_action=suggested,
        agreement_with_risk=agreement,
    )


def _reconcile_agreement(
    stated: Optional[str], suggested: Optional[str], risk: RiskAssessment
) -> str:
    """Prefer the model's stated agreement when valid; otherwise infer it from
    whether its suggested action lines up with the deterministic risk level."""
    if stated in {"AGREE", "PARTIAL", "DISAGREE"}:
        return stated
    if not suggested:
        return "UNKNOWN"
    escalating = {"ENHANCED_VERIFICATION", "ESCALATE"}
    reviewing = {"MANUAL_REVIEW"}
    if risk.level == RiskLevel.HIGH:
        return "AGREE" if suggested in escalating else "DISAGREE"
    if risk.level == RiskLevel.MEDIUM:
        return "AGREE" if suggested in reviewing | escalating else "PARTIAL"
    # LOW
    return "AGREE" if suggested == "NO_ADDITIONAL_ACTION" else "PARTIAL"
